language: c
compiler:
    - gcc
    - clang
before_install:
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - sudo apt-get update -q
    - sudo apt-get install gcc-4.9 -y
script: make clean ; make
